sudo: false

# based on the .travis.yml from the requests package
language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.3"
#  - "3.4"
  - "3.5"
#  - "3.6"
matrix:
  allow_failures:
    - python: "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install ."
# command to run tests
script:
  - make coverage
  - make lint
# command to run after succesful tests
after_success:
  - codecov
